name: "Build BigCommunity ISO"
description: "Builds a BigCommunity ISO image"

inputs:
  distroname:
    type: choice
    description: "Distroname for the ISO"
    required: true
    options:
      - bigcommunity
      - biglinux
    default: "bigcommunity"
  iso_profiles_repo:
    type: choice
    description: "Choice ISO profiles"
    required: true
    options:
      - "https://github.com/talesam/iso-profiles"
      - "https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git"
    default: "https://github.com/talesam/iso-profiles"
  iso_profiles_branch:
    description: "Branch of the ISO profiles repository (optional)"
    required: false
  edition:
    description: "Name of the ISO profile to build"
    required: true
  manjaro_branch:
    description: "Manjaro branch (stable, testing, unstable)"
    required: true
    default: stable
  community_branch:
    description: "Community branch (stable, testing)"
    required: true
  biglinux_branch:
    description: "BigLinux branch (stable, testing)"
    required: true
  scope:
    description: "Build scope (full or minimal)"
    required: false
    default: "full"
  kernel:
    description: "Kernel version (latest, lts, oldLts, xanmod)"
    required: true
  release_tag:
    description: "Release tag for the ISO"
    required: true
  tmate:
    description: "Enable debugging with tmate"
    required: false
    default: false
  office-chooser:
    description: "Include office suite"
    required: false
    default: "false"
  repo_unstable:
    description: "URL for unstable repository"
    required: false
  mirror_dev:
    description: "URL for development mirror"
    required: false
  mirror_unstable:
    description: "URL for unstable BigCommunity mirror"
    required: false
  github_token:
    description: "GitHub token for authentication"
    required: true

outputs:
  iso_path:
    description: "Path to the generated ISO file"
    value: ${{ steps.build.outputs.iso_path }}
  release_name:
    description: "Name of the release"
    value: ${{ steps.prepare-iso.outputs.release_name }}

runs:
  using: "composite"
  steps:
    - name: Display the current user in CONTAINER
      shell: bash
      run: |
        # Display the current user in CONTAINER
        echo "##########################################################################"
        echo "Current host is     : $(hostname)"
        echo "Current user is     : $(whoami)"
        echo "Current user ID is  : $(id -u)"
        echo "Current user details: $(id)"
        echo "##########################################################################"
        df -hT || true
        echo "##########################################################################"
        ls -la /mnt || true
        echo "##########################################################################"

    - name: Setup build environment
      shell: bash
      run: |
        # Setup build environment

        #configure extra repos
        {
          echo "[community-extra]"
          echo "SigLevel = PackageRequired"
          echo "Server = https://repo.communitybig.org/extra/\$arch"
          echo
        } | sudo tee -a /etc/pacman.conf > /dev/null

        # atualizar e instalar pacotes adicionais
        sudo pacman -Syu --quiet --needed --noconfirm --overwrite \* \
          base-devel \
          manjaro-tools-iso-git \
          manjaro-tools-yaml-git \
          manjaro-tools-base-git \
          mktorrent \
          squashfs-tools \
          archiso \
          calamares \
          calamares-tools \
          mkinitcpio \
          shfmt \
          cdrkit \
          ncurses  > /dev/null

    - name: Setup TMATE Session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event.client_payload.tmate == true || inputs.tmate == true}}
      with:
        install-dependencies: false
        detached: true

    - name: Configurar disable-fsync
      shell: bash
      run: |
        # Configurar disable-fsync
        DISABLE_FSYNC_URL="https://raw.githubusercontent.com/biglinux/disable-fsync/main/disable-fsync/usr/lib/disable-fsync.so"
        DISABLE_FSYNC_FILE="/usr/lib/disable-fsync.so"
        PRELOAD_FILE="/etc/ld.so.preload"

        # Faz download do arquivo
        sudo wget "$DISABLE_FSYNC_URL" -O "$DISABLE_FSYNC_FILE"
        # Calcula o hash SHA256 do arquivo baixado
        SHA256SUM=$(curl -s "$DISABLE_FSYNC_URL" | sha256sum | awk '{print $1}')
        # Verifica o hash do arquivo
        echo "${SHA256SUM} ${DISABLE_FSYNC_FILE}" | sha256sum --check || exit 1
        # Adiciona o caminho do arquivo ao PRELOAD_FILE
        sudo sh -c "echo '${DISABLE_FSYNC_FILE}' >> '${PRELOAD_FILE}'"
        # Atualiza o cache de bibliotecas compartilhadas
        sudo ldconfig

    - name: Pull and setup keys
      shell: bash
      run: |
        # Pull and setup Community keys
        git clone https://github.com/biglinux/biglinux-key.git
        sudo install -dm755 /etc/pacman.d/gnupg/
        sudo install -m0644 biglinux-key/usr/share/pacman/keyrings/* /etc/pacman.d/gnupg/
        sudo rm -r biglinux-key

        git clone https://github.com/communitybig/community-keyring.git
        sudo install -m0644 community-keyring/community.gpg /usr/share/pacman/keyrings/
        sudo install -m0644 community-keyring/community-trusted /usr/share/pacman/keyrings/
        sudo install -m0644 community-keyring/community-revoked /usr/share/pacman/keyrings/
        sudo rm -r community-keyring

        # Inicializar o chaveiro do pacman
        #sudo pacman -S biglinux-keyring community-keyring
        sudo pacman-key --init
        sudo pacman-key --populate archlinux
        sudo pacman-key --populate biglinux
        sudo pacman-key --populate community

        # Atualizar os bancos de dados do pacman
        sudo pacman -Sy --quiet --noconfirm

    - name: Ajuste nos hooks do mkinitcpio
      shell: bash
      run: |
        # Ajuste nos hooks do mkinitcpio (se ainda necessário)
        sudo sed -i -e 's/File/Path/' /usr/share/libalpm/hooks/*hook*

    - name: Create mknod /dev/sr0
      shell: bash
      run: |
        # Create with mknod '/dev/sr0'
        sudo mknod /dev/sr0 b 11 0 || true
        sudo chmod 660 /dev/sr0 || true
        sudo chown root:root /dev/sr0 || true

    - name: Declare variáveis de ambiente
      shell: bash
      run: |
        # Declare variáveis de ambiente
        {
          echo "USERNAME=builduser"
          echo "HOME_FOLDER=/home/builduser"
          echo "REPO=${{ inputs.iso_profiles_repo }}"
          echo "EDITION=${{ inputs.edition }}"
          echo "WORK_PATH=/__w/build-iso/build-iso"
          echo "WORK_PATH_ISO_PROFILES=/__w/build-iso/build-iso/iso-profiles"
          echo "PROFILE_PATH=/__w/build-iso/build-iso/iso-profiles/community"
          echo "PROFILE_PATH_EDITION=/__w/build-iso/build-iso/iso-profiles/community/${{ inputs.edition }}"
          echo "PATH_MANJARO_ISO_PROFILES=/usr/share/manjaro-tools/iso-profiles"
          echo "PATH_MANJARO_TOOLS=/usr/share/manjaro-tools"
          echo "VAR_CACHE_MANJARO_TOOLS=/var/cache/manjaro-tools"
          echo "VAR_CACHE_MANJARO_TOOLS_ISO=/var/cache/manjaro-tools/iso"
          echo "DEBUG=${{ inputs.tmate }}"
          echo "DISTRONAME=${{ inputs.distroname || 'bigcommunity' }}"
          echo "MANJAROBRANCH=${{ inputs.manjaro_branch }}"
          echo "COMMUNITYBRANCH=${{ inputs.community_branch }}"
          echo "BIGBRANCH=${{ inputs.biglinux_branch }}"
          echo "KERNEL=${{ inputs.kernel }}"
          echo "RELEASE_TAG=${{ inputs.release_tag }}"
          echo "SCOPE=${{ inputs.scope }}"
          echo "OFFICE=${{ inputs.office-chooser }}"
        } >> "$GITHUB_ENV"

    - name: Build ISO Image ${{ github.event.client_payload.edition || inputs.edition }}
      shell: bash
      run: |
        # Carregando script e building ISO
        if [[ ! -e "$WORK_PATH/mkiso-bigcommunity" ]]; then
          echo "ERRO(L284): Script $WORK_PATH/mkiso-bigcommunity não encontrado ou tamanho zerado!"
          exit 1
        fi
        pushd "$WORK_PATH" || true
        #source "$WORK_PATH/mkiso-bigcommunity"
        #make_iso
        ./mkiso-bigcommunity --automatic

    - name: Set ISO path
      shell: bash
      run: |
        echo "ISO_PATH=$WORK_PATH/$ISO_BASENAME" >> $GITHUB_ENV
