name: ISO Build

on:
  repository_dispatch:
    types:
      - "ISO-*"
  workflow_dispatch:
    inputs:
      distroname:
        type: choice
        description: "Distroname for the ISO"
        required: true
        options:
          - bigcommunity
          - biglinux
        default: "bigcommunity"
      iso_profiles_repo:
        type: choice
        description: "Choice ISO profiles"
        required: true
        options:
          - "https://github.com/talesam/iso-profiles"
          - "https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git"
        default: "https://github.com/talesam/iso-profiles"
      scope:
        type: choice
        description: "Build scope"
        options:
          - full
          - minimal
        default: "full"
      office-chooser:
        type: boolean
        description: "Include office suite"
        required: false
        default: false
      tmate:
        type: boolean
        description: "Enable debugging with tmate"
        required: false
        default: false
      kernel:
        type: choice
        description: "Kernel version"
        options:
          - latest
          - lts
          - oldLts
        default: lts
      manjaro_branch:
        type: choice
        description: "Manjaro branch"
        options:
          - stable
          - testing
          - unstable
        default: stable
      community_branch:
        type: choice
        description: "Community branch"
        options:
          - stable
          - testing
        default: testing
      biglinux_branch:
        type: choice
        description: "BigLinux branch"
        options:
          - stable
          - testing
        default: testing
      edition:
        type: choice
        description: "Edition"
        options:
          - cinnamon
          - cosmic
          - deepin
          - gnome
          - kde
          - xfce
          - wmaker
        default: xfce
        
env:
  TELEGRAM_TOKEN: "${{ secrets.TOKEN_BOT }}"
  CHAT_ID: "${{ secrets.CHAT_ID }}"
  started_by_user: "${{ github.actor }}"
  triggered_by_user: "${{ github.triggering_actor }}"
  repo_path: "${{ secrets.PKGBUILD_DIR }}"
  iso_distroname: "${{ github.event.client_payload.distroname || inputs.distroname || 'chililinux' }}"
  iso_manjaro_branch: "${{ github.event.client_payload.manjaro_branch || inputs.manjaro_branch}}"
  iso_biglinux_branch: "${{ github.event.client_payload.biglinux_branch || inputs.biglinux_branch}}"
  iso_community_branch: "${{ github.event.client_payload.community_branch || inputs.community_branch}}"
  iso_chililinux_branch: "${{ github.event.client_payload.chililinux_branch || inputs.chililinux_branch}}"
  iso_edition: "${{ github.event.client_payload.edition || inputs.edition}}"
  iso_release_tag: "${{ github.event.client_payload.release_tag || inputs.release_tag }}"
  iso_kernel: "${{ github.event.client_payload.kernel || inputs.kernel }}"
  iso_basename: "${iso_distroname}_${iso_branch}_${iso_edition}_${iso_release_tag}"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create a Welcome file
        run: |
          echo "Hello from setup job" > shared_file.txt

      - name: Install dependencies on HOST
        run: |
          #sudo apt-get update
          sudo apt-get autoremove
          sudo apt-get install -y inetutils-tools

      - name: Set up volume directory on HOST
        run: |
          sudo mkdir -p /mnt/var_lib_manjaro_tools_buildiso
          sudo mkdir -p /mnt/var_cache_manjaro_tools_iso

      - name: Capturar hora de início do workflow
        id: start-time
        run: |
          START_TIME=$(date +"%Y-%m-%d %H:%M:%S")  # Hora completa
          START_TIMESTAMP=$(date +%s)  # Timestamp em segundos
          echo "Início do Workflow: $START_TIME"
          echo "START_TIME=$START_TIME" >> $GITHUB_ENV
          echo "START_TIMESTAMP=$START_TIMESTAMP" >> $GITHUB_ENV

      - name: Enviar notificação para o Telegram
        shell: bash
        run: |
          case "${iso_distroname}" in
          bigcommunity) iso_branch="${iso_community_branch}";;
          biglinux) iso_branch="${iso_biglinux_branch}";;
          chililinux) iso_branch="${iso_chililinux_branch}";;
          manjaro) iso_branch="${iso_manjaro_branch}";;
          esac

          MESSAGE="🚀 <b>[step 0/6] build-iso - INICIANDO WORKFLOW</b>
          <b>Job:</b> <code>#${GITHUB_RUN_NUMBER}</code>
          <b>Workflow:</b> <code>build-iso/edition.yml</code>
          <b>Iniciado/Triggered:</b> <code>${started_by_user}/${triggered_by_user}</code>
          <b>Inicio:</b> <code>${{ env.START_TIME }}</code>
          <b>Distroname:</b> <code>${iso_distroname}</code>
          <b>Edition:</b> <code>${iso_edition}</code>
          <b>Manjaro Branch:</b> <code>${iso_manjaro_branch}</code>
          <b>BigLinux Branch:</b> <code>${iso_biglinux_branch}</code>
          <b>BigCommunity Branch:</b> <code>${iso_community_branch}</code>
          <b>ChiliLinux Branch:</b> <code>${iso_chililinux_branch}</code>
          <b>Release:</b> <code>${iso_release_tag}</code>
          <b>Kernel:</b> <code>${iso_kernel}</code>
          <b>ISO Name:</b> <code>${iso_distroname}_${iso_branch^^}_${iso_edition}_${iso_release_tag}</code>"

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="${MESSAGE}" \
            -d parse_mode="HTML"
  
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shared-file
          path: shared_file.txt

      - name: Display the current user in host
        run: |
          # Display the current user in host
          echo "#########################################"
          echo "Current host is: $(hostname)"
          echo "Current user is: $(whoami)"
          echo "Current user ID is: $(id -u)"
          echo "Current user details:"
          id
          echo "#########################################"
          df -hT
          echo "#########################################"
          ls -lah --color=auto /mnt
          echo "#########################################"

  build:
    name: Build ISO ${{ github.event.client_payload.distroname || inputs.distroname }} ${{ github.event.client_payload.edition || inputs.edition }}
    runs-on: ubuntu-latest
    needs: [setup] # Espera o job "setup" terminar
    container:
      image: talesam/community-build:1.5
      options: --privileged
      volumes:
        - /mnt/var_lib_manjaro_tools_buildiso:/var/lib/manjaro-tools/buildiso
        - /mnt/var_cache_manjaro_tools_iso:/var/cache/manjaro-tools/iso

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: shared-file

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          #fetch-depth: 0    # Todo o histórico de commits seja baixado
          fetch-depth: 1 # Apenas o commit mais recente da branch será baixado
  
      - name: Display the current user in host
        shell: bash
        run: |
          # Display the current user in host
          echo "#########################################"
          echo "Current host is: $(hostname)"
          echo "Current user is: $(whoami)"
          echo "Current user ID is: $(id -u)"
          echo "Current user details:"
          id
          echo "#########################################"
          df -hT
          echo "#########################################"
          ls -lah --color=auto /mnt
          echo "#########################################"
          tree -d /mnt
          echo "#########################################"

      - name: Set release tag automatically
        id: date
        run: |
          # Set release tag manually
          echo "RELEASE_TAG=$(date '+%Y-%m-%d_%H-%M')" >> "$GITHUB_ENV"
          
      - name: Build ISO
        uses: ./
        id: build
        with:
          # Parâmetros básicos da ISO
          distroname: ${{ github.event.client_payload.distroname || inputs.distroname || 'bigcommunity' }}
          edition: ${{ github.event.client_payload.edition || inputs.edition}}
          #release_tag: ${{ github.event.client_payload.release_tag || inputs.release_tag }}
          release_tag: ${{ env.RELEASE_TAG }}
          kernel: ${{ github.event.client_payload.kernel || inputs.kernel }}
          scope: ${{ github.event.client_payload.scope || inputs.scope }}
          office-chooser: ${{ github.event.client_payload.office-chooser || inputs.office-chooser }}

          # Parâmetros de branches
          manjaro_branch: ${{ github.event.client_payload.manjaro_branch || inputs.manjaro_branch }}
          community_branch: ${{ github.event.client_payload.community_branch || inputs.community_branch }}
          biglinux_branch: ${{ github.event.client_payload.biglinux_branch || inputs.biglinux_branch }}

          # Depuração
          tmate: ${{ github.event.client_payload.tmate || inputs.tmate != false && inputs.tmate }}

          # Tokens e segredos
          github_token: ${{ secrets.TOKEN_RELEASE }}

          # Parâmetros adicionais (se necessário)
          iso_profiles_repo: ${{ github.event.client_payload.iso_profiles_repo || inputs.iso_profiles_repo }}
          # iso_profiles_branch: ${{ github.event.client_payload.iso_profiles_branch || inputs.iso_profiles_branch }}

      - name: Set ISO path
        run: |
          # Set ISO path
          echo "ISO_PATH=${{ env.WORK_PATH }}/${{ env.ISO_BASENAME }}" >> $GITHUB_ENV

      - name: Calculate ISO MD5 Hash
        shell: bash
        run: |
          echo "Calculating MD5 hash for ISO file ${ISO_PATH}"
          if [[ -f "${ISO_PATH}" ]]; then
            md5sum "${ISO_PATH}" > "${ISO_PATH}.md5"
            echo "MD5 hash calculated and saved:"
            cat "${ISO_PATH}".md5
          else
            echo "Error: ISO file not found at ${ISO_PATH}"
            exit 1
          fi

      - name: Prepare ISO for release
        id: prepare-iso
        shell: bash
        run: |
          ls -lah
          release=$(basename "${ISO_PATH}" .iso)
          zip -j -0 -s 2000m ${release}.zip "${ISO_PATH}"
          echo "release_name=${release}" >> "$GITHUB_OUTPUT"
          echo "ISO prepared for release"

          # Imprimir a variável ISO_PATH para depuração
          echo "ISO_PATH (iso) : ${ISO_PATH}"
          echo "ISO_PATH (md5) : ${ISO_PATH}.md5"
          echo "ISO_PATH (pkgs): ${ISO_PATH}.pkgs"
          echo "release        : ${release}"
          echo "release_name   : ${release_name}"

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.prepare-iso.outputs.release_name }}
          path: |
            ${{ env.ISO_PATH }}
            ${{ env.ISO_PATH }}.md5
            ${{ env.ISO_PATH }}.pkgs

      - name: Create Release
        if: ${{ (github.event.client_payload.manjaro_branch || inputs.manjaro_branch) == 'stable' && (github.event.client_payload.community_branch || inputs.community_branch) == 'stable' && (github.event.client_payload.biglinux_branch || inputs.biglinux_branch) == 'stable' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ISO_PATH }}
            ${{ env.ISO_PATH }}.md5
            ${{ env.ISO_PATH }}.pkgs
            ${{ steps.prepare-iso.outputs.release_name }}.z*
          tag_name: ${{ github.event.client_payload.release_tag || inputs.release_tag }}
          name: ${{ steps.prepare-iso.outputs.release_name }}
          generate_release_notes: true
