# Nome do workflow
name: M:Testing / B:Unstable - Unstable KDE

# Gatilhos para o workflow
on:
  workflow_dispatch:  # Permite a execução manual do workflow
    inputs:
      debug_enabled:  # Input para habilitar o modo de depuração
        type: boolean
        description: 'With TMATE'
        required: false
        default: false
        
  schedule:  # Executa automaticamente toda sexta-feira às 05:00
    - cron:  '0 5 * * 5'
    
  repository_dispatch:  # Permite a execução através de eventos de webhook
    types:
      - webhook
      - '**'

# Jobs do workflow
jobs:
  # Job para preparar a release
  prepare-release:
    runs-on: ubuntu-20.04  # Define a máquina virtual a ser usada
    steps:
      - id: time
        uses: nanzm/get-time-action@v1.1  # Ação para obter o tempo atual
        with:
          format: 'YYYY-MM-DD_HH-mm'
    outputs:
      release_tag: ${{ steps.time.outputs.time }}  # Saída do job
      
  # Job para construir a release
  build-release:
    runs-on: ubuntu-20.04  # Define a máquina virtual a ser usada
    needs: [prepare-release]  # Depende do job prepare-release
    strategy:
      matrix:
        NAME: [biglinux] # Define o nome do SO
        EDITION: [kde] # Define a edição
        MANJAROBRANCH: [testing] # Define a branch do Manjaro (stable, testing ou unstable)
        BIGBRANCH: [unstable] # Define a branch do Biglinux (stable ou testing)
        KERNEL: [latest] # Define a versão do kernel (atualLts, latest)
        
    steps:
      - name: Build and Upload GitHub
        uses: talesam/build-iso@main  # Ação para construir e fazer upload da ISO
        with:
          name: ${{ matrix.name }}
          edition: ${{ matrix.edition }}
          manjarobranch: ${{ matrix.manjarobranch }}
          bigbranch: ${{ matrix.bigbranch }}
          kernel: ${{ matrix.kernel }}
          extrarepo: ${{ matrix.extrarepo }}
          iso-profiles-repo: 'https://github.com/talesam/iso-profiles'
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
          tmate: ${{ inputs.debug_enabled }}
          repo-unstable: ${{ secrets.REPO_UNSTABLE }}
          mirror-dev: ${{ secrets.MIRROR_DEV }}
          
      # Configuração do TMATE para sessão de depuração
      - name: Setup TMATE Session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      # Verifica MD5SUM
      - name: Verify md5sum
        shell: bash
        run: |
          mkdir mnt
          find -type f -iname "*.iso" -exec sudo mount -o loop {} mnt \;
          pushd mnt/manjaro/x86_64/
            for i in *.md5; do 
              if [ "$(md5sum -c $i | cut -d " " -f2)" != "OK" ]; then
                echo "deu ruim no md5dum do arquivo $i"
                exit 1
              else
                echo "md5sum do arquivo $i está OK"
              fi
            done
          popd
          sudo umount mnt

      # Prepara Upload
      - name: upload-prepare
        shell: bash -O extglob {0}
        run: |
          echo "## ssh setup"
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
      
      # Configuração do TMATE para sessão de depuração
      - name: Setup TMATE Session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      
      # Upload da ISO
      - name: Publish Package on GitHub
        shell: bash
        run: |
          # Enviar arquivo ISO e MD5 para o Telegram
          telegram_token="${{ secrets.ISO_TOKEN_BOT }}"
          chat_id="${{ secrets.ID_CANAL_TELEGRAM }}"

          # Encontrar o nome do arquivo ISO
          iso_file=$(find . -name "*.iso" | head -n 1)
          iso_name=$(basename "$iso_file")
          tag_name="${iso_name%.*}"

          # Encontrar o arquivo MD5 correspondente
          md5_file="${iso_file%.iso}.md5"

          # Enviar mensagem com o nome da tag
          curl -s -X POST "https://api.telegram.org/bot${telegram_token}/sendMessage" \
              -d "chat_id=${chat_id}" \
              -d "text=*${tag_name}*\n\n" \
              -d "parse_mode=MarkdownV2"

          # Enviar arquivo ISO
          curl -s -X POST "https://api.telegram.org/bot${telegram_token}/sendDocument" \
              -F "chat_id=${chat_id}" \
              -F "document=@${iso_file}" \
              -F "caption=💿 ${iso_name}" \
              > /dev/null

          if [ $? -eq 0 ]; then
              echo "✅ Arquivo ISO enviado com sucesso"
          else
              echo "❌ Erro ao enviar arquivo ISO"
          fi

          # Enviar arquivo MD5
          curl -s -X POST "https://api.telegram.org/bot${telegram_token}/sendDocument" \
              -F "chat_id=${chat_id}" \
              -F "document=@${md5_file}" \
              -F "caption=🔑 ${md5_file##*/}" \
              > /dev/null

          if [ $? -eq 0 ]; then
              echo "✅ Arquivo MD5 enviado com sucesso"
          else
              echo "❌ Erro ao enviar arquivo MD5"
          fi

          # Quebra o arquivo e faz upload
          ls -lh
          release=$(find . -name *.iso | cut -d "/" -f2 | sed 's/.iso//')
          zip -j -0 -s 1950m ${release}.zip ${release}.iso
          ls -lh
          echo ${{ secrets.TOKEN_RELEASE }} | gh auth login --with-token
          gh release create ${release} --title ${release} --repo ${{ secrets.REPO_ISO }} --notes "automated release from CI/CD" || echo "release already exists"
          for i in *.z* *.md5 *.pkgs; do
            gh release upload ${release} --repo ${{ secrets.REPO_ISO }} --clobber $i
          done
